# coslatte's starship template

# LEGO THEME
format = """
[▟](fg:red)\
$os\
$username\
[▛](fg:red bg:maroon)\

[▟](fg:maroon bg:red)\
$directory\
[▛](fg:maroon bg:gold)\

[▟](fg:gold bg:maroon)\
$localip\
[▛](fg:gold bg:yellow)\

[▟](fg:yellow bg:gold)\
$git_branch\
$git_status\
$git_metrics\
[▛](fg:yellow bg:flamingo)\

[▟](fg:flamingo bg:yellow)\
$c\
$rust\
$nodejs\
$java\
$python\
[▛](fg:flamingo bg:lavender)\

[▟](fg:lavender bg:flamingo)\
$time\

[▛](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'palette1'

[palettes.palette1]
text = "#ccccb5"
crust = "#151a21"
base = "#1b2028"

red = "#e74c3c"
maroon = "#c0392b"
gold = "#f39c12"
yellow = "#e74c3c"
flamingo = "#8e44ad"
lavender = "#16a085"
blue = "#23a9d5"

#############
# [MODULES] #
#############
[os]
disabled = false
style = "bg:red fg:crust"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲"
Linux = "󰌽"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:maroon fg:crust"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "⸫ "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[localip]
ssh_only = false
format = '[ 𐋃 $localipv4 ]($style)'
style = "bg:gold fg:crust"
disabled = false

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status $ahead_behind)](fg:crust bg:yellow)]($style)'

[git_metrics]
added_style = 'bg:blue fg:crust'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

##########################
# [PROGRAMING LANGUAGES] #
##########################
[nodejs]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol($version) ](fg:crust bg:flamingo)]($style)'

[c]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol ($version) ](fg:crust bg:flamingo)]($style)'

[java]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol (Java v$version) ](fg:crust bg:flamingo)]($style)'

[rust]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol ($version) ](fg:crust bg:flamingo)]($style)'

[python]
symbol = ""
style = "bg:flamingo"
format = '[[ $symbol ($version) (\($virtualenv\)) ](fg:crust bg:flamingo)]($style)'

##########
# [TIME] #
##########
[time]
disabled = false
use_12hr = true
utc_time_offset = "local"
time_format = "%R"
style = "bg:lavender"
format = '[[ t = $time ](fg:crust bg:lavender)]($style)'

######################
# [COMMAND DURATION] #
######################
[cmd_duration]
show_milliseconds = true
format = " ⯌ in $duration"
style = "fg:crust"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

###############
# [CHARACTER] #
###############
[character]
disabled = false
success_symbol = '[✎](fg:blue)'
error_symbol = '[✗](fg:red)'
vimcmd_symbol = '[⟀](fg:flamingo)'
vimcmd_replace_one_symbol = '[⟀](italic fg:lavender)'
vimcmd_replace_symbol = '[⟀](italic fg:lavender)'
vimcmd_visual_symbol = '[⟀](italic fg:yellow)'

