# coslatte - 2026

# RGB SCHEMA (LEGO INHERITED)
format = """
[▟](fg:r)\
$os\
$username\
$directory\
[▛](fg:r bg:b)\

[▟](fg:b bg:r)\
$git_branch\
$git_status\
$git_metrics\
[▛](fg:b bg:g)\

[▟](fg:g bg:b)\
$c\
$rust\
$nodejs\
$java\
$python\

[▛](fg:g)\
$cmd_duration\
$line_break\
$character"""

palette = 'palette2'

[palettes.palette1]
text = "#ccccb5"
crust = "#151a21"
base = "#1b2028"
red = "#e74c3c"
maroon = "#c0392b"
gold = "#f39c12"
orange = "#e76a3c"
flamingo = "#8e44ad"
lavender = "#16a085"
new_blue = "#23a9d5"
green = "#59ba70"

[palettes.palette2]
text = "#f5f7f9"
crust = "#172231"
base = "#11191f"
r = "#e03030"
g = "#2fdd66"
b = "#1c69d6"

#############
# [MODULES] #
#############
[os]
disabled = false
style = "bg:r fg:crust"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲 "
Linux = "󰌽 "

[username]
show_always = false
style_user = "bg:r fg:crust"
style_root = "bg:r fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:r fg:crust"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "⸫ "

[directory.substitutions]
"Music" = " 󰝚"
"Dev" = " 󰲋"

[git_branch]
symbol = ""
style = "bg:b"
format = '[[ $symbol $branch ](fg:crust bg:b)]($style)'
disabled = false

[git_status]
style = "bg:b"
format = '[\[($all_status $ahead_behind)\](fg:crust bg:b)]($style)'
disabled = true

[git_metrics]
added_style = 'bg:b fg:g'
deleted_style = 'bg:b fg:r'
format = '[ \[+$added\]]($added_style)(bg:b fg:crust)[\[-$deleted\] ]($deleted_style)'
disabled = false

##########################
# [PROGRAMING LANGUAGES] #
##########################
[nodejs]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) ](fg:crust bg:g)]($style)'

[c]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) ](fg:crust bg:g)]($style)'

[java]
symbol = ""
style = "bg:g"
format = '[[ $symbol (Java v$version) ](fg:crust bg:g)]($style)'

[rust]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) ](fg:crust bg:g)]($style)'

[python]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) (\($virtualenv\)) ](fg:crust bg:g)]($style)'

##########
# [TIME] #
##########
[time]
disabled = false
use_12hr = true
utc_time_offset = "local"
time_format = "%R"
style = "bg:r"
format = '[[ t = $time ](fg:crust bg:r)]($style)'

######################
# [COMMAND DURATION] #
######################
[cmd_duration]
disabled = false
show_milliseconds = true
format = " ⯌ $duration"
style = "fg:crust"
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

###############
# [CHARACTER] #
###############
[character]
disabled = false
success_symbol = '[✎](fg:g)'
error_symbol = '[✗](fg:r)'
vimcmd_symbol = '[⟀](fg:g)'
vimcmd_replace_one_symbol = '[⟀](italic fg:g)'
vimcmd_replace_symbol = '[⟀](italic fg:g)'
vimcmd_visual_symbol = '[⟀](italic fg:g)'


