# coslatte - 2026

# RGB SCHEMA
format = """
[▟](fg:r)\
$os\
$username\
$directory\
[▛](fg:r bg:b)\

[▟](fg:b bg:r)\
$git_branch\
$git_status\
$git_metrics\
[▛](fg:b bg:g)\

[▟](fg:g bg:b)\
$c\
$rust\
$nodejs\
$java\
$python\

[▛](fg:g)\
$cmd_duration\
$line_break\
$character"""

palette = 'rgb'

[palettes.rgb]
text = "#f5f7f9"
crust = "#172231"
base = "#11191f"
r = "#e03030"
g = "#2aca5d"
b = "#1e64c6"

#############
# [MODULES] #
#############
[os]
disabled = false
style = "bg:r fg:text"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲 "
Linux = "󰌽 "

[username]
show_always = false
style_user = "bg:r fg:text"
style_root = "bg:r fg:text"
format = '[ $user ]($style)'

[directory]
style = "bg:r fg:text"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "⸫ "

[directory.substitutions]
"Music" = " 󰝚"
"Dev" = " 󰲋"

[git_branch]
symbol = ""
style = "bg:b"
format = '[[ $symbol $branch ](fg:text bg:b)]($style)'
disabled = false

[git_status]
style = "bg:b"
format = '[\[($all_status $ahead_behind)\](fg:text bg:b)]($style)'
disabled = true

[git_metrics]
added_style = 'bg:base fg:g'
deleted_style = 'bg:base fg:r'
format = '[\[+$added\]]($added_style)[\[-$deleted\]]($deleted_style)'
disabled = false

##########################
# [PROGRAMING LANGUAGES] #
##########################
[nodejs]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) ](fg:text bg:g)]($style)'

[c]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) ](fg:text bg:g)]($style)'

[java]
symbol = ""
style = "bg:g"
format = '[[ $symbol (Java v$version) ](fg:text bg:g)]($style)'

[rust]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) ](fg:text bg:g)]($style)'

[python]
symbol = ""
style = "bg:g"
format = '[[ $symbol ($version) (\($virtualenv\)) ](fg:text bg:g)]($style)'

##########
# [TIME] #
##########
[time]
disabled = false
use_12hr = true
utc_time_offset = "local"
time_format = "%R"
style = "bg:r"
format = '[[ t = $time ](fg:text bg:r)]($style)'

######################
# [COMMAND DURATION] #
######################
[cmd_duration]
disabled = false
show_milliseconds = true
format = " ⯌ $duration"
style = "fg:text"
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false

###############
# [CHARACTER] #
###############
[character]
disabled = false
success_symbol = '[✎](fg:g)'
error_symbol = '[✗](fg:r)'
vimcmd_symbol = '[⟀](fg:g)'
vimcmd_replace_one_symbol = '[⟀](italic fg:g)'
vimcmd_replace_symbol = '[⟀](italic fg:g)'
vimcmd_visual_symbol = '[⟀](italic fg:g)'


